api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    show_webby: false
    enable_swagger_ui: true
    enable_re_doc: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Authentication/UserInterface/ApiPlatform/Resource/'
            - '%kernel.project_dir%/src/Authentication/UserInterface/ApiPlatform/Payload/'
            - '%kernel.project_dir%/src/User/UserInterface/ApiPlatform/Resource/'
            - '%kernel.project_dir%/src/Messaging/UserInterface/ApiPlatform/Resource/'
    patch_formats:
        json:
            - 'application/merge-patch+json'
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    exception_to_status:
        \App\Common\Domain\Exception\ValidationFailed: 400
        \App\Common\Domain\Exception\LogicFailed: 400
        \App\Common\Domain\Exception\ResourceNotFound: 404