@baseUrl = https://localhost:8000/api
#@authToken = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjbGllbnRJZCI6Ijc1ODljOTBjLTBlYWYtNGZhNC1iZWNhLWU1OTBlOTY3YzVmMCIsImVtYWlsIjoiam9zZUBtYWlsLmNvbS5iciIsImZpcnN0TmFtZSI6Ikpvc2UiLCJsYXN0TmFtZSI6IlNpbHZhIn0.GxoiFtVL3lSVF7dfk6JFdD6siQZ_jcRj9g6_zjH7LZ2vIB0EA13jkouaBaqCACEHRvxAU2kCWt_GSsINbiZdrHloOHHYO_jOdcVwAkN-SdPE74iPb9DTpXLfxs78tI250Slu3TfbMFMAaEA5w22qoVYcbZZIUbZQqjCTH32mej6SOmZwOWRrSNCol9pY7uv4crgQ-5wgrpnSsshSRRtbPJM69Aeia7QHyrU8B06fKFu2sOEvHkkw-YjW7mrw5LVXCnFFvziw-vsroihaI6UiMeFetalDmNv_dmXIfPGYjL_SaxzO3J5B_uX1RKqyqNV_OAY0R4iflATL_YnsrEmiXXxC2e4_zBUdJTcMfTDoZTUPOPx5yZ3GW3loliGwi1DID8D9EfD7aEnSfWEC3b176T6Qu-tdpv9labO2Ra66Dej3rQRpBrlSdMXoONOOIVo3YxIOwq0jcyMW2ALSVJZX0WmdKFsDHdHcswvm-jo7YLYAYjv4_wLaG8kTZBn9fUcl6PnHGVWGjcMPvL1GFHvbkTLoXFt241az7YzSxH9_I_hFW4qoRnSsIVhz9wCxi4eKruvis_MiP0kzVEfMHIEOy2yEsKzoXOMuS9wbut8eyHg91AaubCwBD8Qd7v3EXyQDxfHYK-kK1_Hf1_BE2MZuuC-hp0_e-n8Ks4Njihs3JmE
@authToken = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjbGllbnRJZCI6IjIxZWUyMGViLTM0YjktNGZmMi04MmQ2LWRlMDJjNDczNzg0MyIsImVtYWlsIjoiam9zZUBtYWlsLmNvbS5iciIsImZpcnN0TmFtZSI6Ikpvc2UiLCJsYXN0TmFtZSI6IlNpbHZhIn0.J3z6FLSkx_tMlJydts2bdyFjBDoWS3YHIVuMyrq2iJPMtp14hYaxWTRk0vCFC3uDtqiURsz_1OMb3GmjOfU9RERKV6w-4JisYLOjk9tFyTkXDFgh5jEPtBqFUZC_kE9MUYnM3c0JhhP5zsIdpMsH1BwYMYKetFSL17GKuD6EXMg90O7zyjbWJsbn-lJFcBO2zJK9ttFP6PeUVfaSss4Q2dsK-PubMjsKiWlWh3eid2cV90YfRlzHm_PnhOkPd--qt6GyR5yloYSO1Le3LPgjj-5wH1m-f1bwNmgQZquopyKArhtJh3j9_JtsabAA22UtqDDoM-W4DVC93F7umNzne1L7jBI-Az5U6ILjNFPnTVy8a_eCSztGk8jQc2V3oTRAVcIWRzT9zghrpRTfRvpgBUur6u8pICXek4p1Lmlmp03SZHavmagliUc9Crg8cl3pxeXrRNYmuspNu3WC_Pq2uh8XbVgbXduNNTvNw5uGxWeZl-J0wBOYmyL-Ttr46Z8fedoaYkPLhOFUDGBv0O42amqfEaBVRGdAvd7_VcsK8PJsoVvoeA5RNVPnjp98XxnzaXPwS4DYSTHLyMTLuFnfbos5au1XFYZwOdC3HBEHaxuaRNJG5lU0FKugewj8dhNaj4rjo1HLaBT7uLndf0cDGcz4f3VvhKbXcIYVuHFMktM

GET {{baseUrl}}/actuator/info

###

POST {{baseUrl}}/auth/login
content-type: application/ld+json

{
    "email": "jose@mail.com.br",
    "password": "p@ssw0rd"
}

###

POST {{baseUrl}}/auth/signup
content-type: application/ld+json

{
    "firstName": "Jose",
    "lastName": "Silva",
    "email": "jose@mail.com.br",
    "password": "p@ssw0rd",
    "passwordConfirm": "p@ssw0rd"
}

###

PUT {{baseUrl}}/clients/21ee20eb-34b9-4ff2-82d6-de02c4737843
content-type: application/ld+json

{
    "firstName": "Pedro",
    "lastName": "Costa",
    "email": "pedro@mail.com.br"
}

###

GET {{baseUrl}}/clients
Authorization: {{authToken}}

###

GET {{baseUrl}}/clients/21ee20eb-34b9-4ff2-82d6-de02c4737843
Authorization: {{authToken}}
